drop table users if exists;
CREATE TABLE users (id bigint generated by default as identity (start with 0, increment by 1), name VARCHAR(100));
insert into users (name) values('John');
insert into users (name) values('Smith');